
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rnals
 */
public class SignupFrame extends javax.swing.JFrame {
    
    DB_MAN DBM = new DB_MAN();
    String strSQL = "select * From columns";
    
    /**
     * Creates new form SignupFrame
     */
    public SignupFrame() {
        initComponents();
         SignupFrame.super.setSize(700, 500);
         SignupFrame.super.setLocation(500, 120);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSignup = new javax.swing.JPanel();
        txtPasswordCheck = new javax.swing.JPasswordField();
        lblSignupTitle = new javax.swing.JLabel();
        lblPasswordCheck = new javax.swing.JLabel();
        txtUserpwd = new javax.swing.JPasswordField();
        lblID = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        btnSignup = new javax.swing.JButton();
        txtUserId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnSignup.setBackground(new java.awt.Color(255, 255, 255));

        txtPasswordCheck.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        txtPasswordCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordCheckActionPerformed(evt);
            }
        });

        lblSignupTitle.setFont(new java.awt.Font("새굴림", 1, 32)); // NOI18N
        lblSignupTitle.setText("회원가입");

        lblPasswordCheck.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPasswordCheck.setText("Password확인 :");

        txtUserpwd.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        txtUserpwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserpwdActionPerformed(evt);
            }
        });

        lblID.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblID.setText("ID :");

        lblPassword.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblPassword.setText("Password :");

        lblEmail.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblEmail.setText("이메일 :");

        txtUserEmail.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        txtUserEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserEmailActionPerformed(evt);
            }
        });

        btnSignup.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnSignup.setText("회원가입");
        btnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignupActionPerformed(evt);
            }
        });

        txtUserId.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        lblName.setText("이름 :");

        txtUserName.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("맑은 고딕", 1, 14)); // NOI18N
        btnBack.setText("로그인 ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSignupLayout = new javax.swing.GroupLayout(pnSignup);
        pnSignup.setLayout(pnSignupLayout);
        pnSignupLayout.setHorizontalGroup(
            pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSignupLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblPasswordCheck)
                        .addComponent(lblPassword, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                    .addComponent(txtUserEmail)
                    .addComponent(txtUserpwd)
                    .addComponent(txtPasswordCheck)
                    .addComponent(txtUserId))
                .addGap(241, 241, 241))
            .addGroup(pnSignupLayout.createSequentialGroup()
                .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSignupLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(lblSignupTitle))
                    .addGroup(pnSignupLayout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSignup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSignupLayout.setVerticalGroup(
            pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSignupLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblSignupTitle)
                .addGap(31, 31, 31)
                .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserpwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(9, 9, 9)
                .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordCheck, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasswordCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblName))
                .addGap(10, 10, 10)
                .addGroup(pnSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEmail)
                    .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnSignup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSignup, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void txtUserpwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserpwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserpwdActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // TODO add your handling code here:
       String useridd = null;
       strSQL = "select userid from Point.user where userid = '" + txtUserId.getText() + "'" ;
                             
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strSQL);
            while(DBM.DB_rs.next()){
            useridd = (DBM.DB_rs.getString("userid"));
            }            
        DBM.DB_rs.close();
        DBM.dbClose();          
        }
        
        catch(Exception e){
            System.out.println("SQLException:" + e.getMessage());
        }
        if(txtUserId.getText().equals("")){
            JOptionPane.showMessageDialog(null, "아이디를 입력하세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;                   
        }if(txtUserId.getText().equals(useridd)){
            JOptionPane.showMessageDialog(null, "아이디가 있습니다", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }if(txtUserpwd.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "패스워드를 입력하세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }if(!Arrays.equals(txtUserpwd.getPassword(),txtPasswordCheck.getPassword())){
            JOptionPane.showMessageDialog(null, "비밀번호가 맞지 않습니다.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        
        }if(txtUserName.getText().equals("")){
            JOptionPane.showMessageDialog(null, "이름을 입력하세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;        
        }
        
        if(txtUserEmail.getText().equals("")){
            JOptionPane.showMessageDialog(null, "이메일을 입력하세요.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        if(!txtUserEmail.getText().contains("@")){
            JOptionPane.showMessageDialog(null, "이메일 형식에 맞지 않습니다.", "ERROR_MESSAGE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        else{
        strSQL ="INSERT INTO user values(";
        strSQL +="'"+txtUserId.getText()+"',";
        strSQL +="hex(aes_encrypt('"+txtUserpwd.getText()+"','a')),";
        //strSQL +="'"+userpwd.getText()+"',";
        strSQL +="'"+txtUserName.getText()+"',";
        strSQL +="hex(aes_encrypt('"+txtUserEmail.getText()+"','a')),";
        strSQL +=10000+")";
        
        try{
            DBM.dbOpen();
            DBM.DB_stmt.executeUpdate(strSQL);
            DBM.dbClose();
            
        } catch(Exception e){
            System.out.println("SQLException" + e.getMessage());            
        }
        
        JOptionPane.showMessageDialog(null, "회원가입 되었습니다.");
        loginFrame lf = new loginFrame();
        lf.setVisible(true);
        this.dispose();
         
        }
        
        
    }//GEN-LAST:event_btnSignupActionPerformed

    private void txtPasswordCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordCheckActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtUserEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserEmailActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUserEmailActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        loginFrame lf = new loginFrame();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignupFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignupFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSignup;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordCheck;
    private javax.swing.JLabel lblSignupTitle;
    private javax.swing.JPanel pnSignup;
    private javax.swing.JPasswordField txtPasswordCheck;
    private javax.swing.JTextField txtUserEmail;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPasswordField txtUserpwd;
    // End of variables declaration//GEN-END:variables
}
